package com.michaelGV;

public class Surname {
    private static String[] surnames = {"Torres", "Muhlenkamp", "Bourbonnais", "Siliezar", "Oberst", "Goring", "Ditucci", "Che", "Behme", "Ehrhardt", "Bringle", "Isabella", "Eisenhaver", "Tatsuta", "Ternasky", "Steinert", "Claytor", "Hoelscher", "Erath", "Stipp", "Durnin", "Osterberger", "Sniezek", "Lawary", "Delea", "Berrell", "Winkey", "Konick", "Nosworthy", "Flaggs", "Glasper", "Andringa", "Heart", "Blixt", "Pflanz", "Bolden", "Schlieter", "Fontanilla", "Zlotnick", "Drust", "Olcus", "Toth", "Mangas",
            "Havermann", "Phanthavongsa", "Raybould", "Katzaman", "Seurer", "Mode", "Len", "Miene", "Stieb", "Pontoriero", "Digeorgio", "Aldape", "Anglada", "Sholar", "Lillard", "Striegel", "Jalkut", "Bolay", "Demosthenes", "Dougan", "Coxum", "Demaris", "Shaer", "Shimon", "Skeldon", "Bramlett", "Cannedy", "Berrong", "Mushrush", "Eoff", "Lebeouf", "Tritle", "Wanty", "Brodmerkel", "Taylan", "Teque", "Kalish", "Sanlatte", "Beer", "Fougere", "Ravelo", "Wandel", "Covarrubia",
            "Golida", "Null", "Catanach", "Harriger", "Smith", "Bakken", "Lillian", "Jastrzebski", "Ehlke", "Senosk", "Radcliffe", "Kinkelaar", "Vangemert", "Mcglockton", "Toppins", "Gouldie", "Hofstetter", "Bonett", "Mcclaugherty", "Brenda", "Manzo", "Korgie", "Smyers", "Menson", "Belkin", "Aujla", "Gore", "Dolph", "Coiro", "Raff", "Kortright", "Reisman", "Craigen", "Daking", "Sylney", "Deuschel", "Guzewicz", "Walwyn", "Rutkin", "Saephan", "Kochmanski", "Pulte", "Thang",
            "Derastel", "Estrem", "Cardozo", "Csensich", "Neisius", "Jim", "Strohmeyer", "Iarossi", "Drevs", "Mantegna", "Tamburello", "Kelso", "Pacella", "Carstensen", "Pierro", "Whyne", "Leiby", "Moulton", "Landry", "Corner", "Hubric", "Illich", "Lagorio", "Schleimer", "Vellutini", "Hegre", "Nesline", "Pizzini", "Kanas", "Nevilles", "Bali", "Pronto", "Dieffenbach", "Shamas", "Valis", "Schwuchow", "Kauzlarich", "Schelp", "Kinnie", "Skowron", "Teall", "Chabez", "Averyt",
            "Penrod", "Senate", "Agre", "Deneui", "Pote", "Evenson", "Vant", "Studwell", "Boroughs", "Brookshier", "Wyms", "Shaheen", "Seiple", "Amezcua", "Vandorp", "Gruben", "Hedge", "Skordahl", "Nembhard", "Jasinski", "Espenschied", "Perteet", "Hagerty", "Mcmillon", "Mcnertney", "Vanderbilt", "Conigliaro", "Raif", "Woehrle", "Taton", "Hoekman", "Disandro", "Batch", "Gilstad", "Garverick", "Mall", "Haza", "Mccargo", "Liberato", "Klingelhoets", "Palmatier", "Wohner",
            "Loyborg", "Styborski", "Fredricks", "Trivette", "Lowes", "Buffum", "Correale", "Goodie", "Berbes", "Boundy", "Soppeland", "Kanno", "Minock", "Provence", "Izaquirre", "Grumbach", "Pourvase", "Garron", "Dimariano", "Iguina", "Hollingworth", "Londagin", "Pro", "Cotsis", "Raleigh", "Sams", "Menges", "Cheatam", "Osterholt", "Semonis", "Bullaro", "Zerko", "Steinhart", "Pardall", "Trompeter", "Demmert", "Kela", "Steeb", "Hazell", "Gadway", "Cuartas", "Buntain",
            "Baron", "Etsitty", "Aurrichio", "Maloff", "Coenen", "Rabenstein", "Nogueira", "Derosia", "Beacham", "Wojenski", "Groman", "Sek", "Metzel", "Alliston", "Balis", "Satmary", "Ellars", "Duenas", "Nilson", "Herbig", "Polikoff", "Kassay", "Kaid", "Hollender", "Vanmatre", "Testani", "Thurrell", "Merati", "Setlak", "Siers", "Frick", "Minecci", "Haggberg", "Rabbe", "Sulzer", "Vargas", "Sterba", "Logoleo", "Roberie", "Henrichs", "Saulters", "Verplanck", "Kobialka",
            "Knutson", "Didier", "Florey", "Maharaj", "Bahde", "Schweinfurth", "Aagaard", "Pool", "Bobsin", "Dotson", "Queal", "Dippel", "Curling", "Kordas", "Brickett", "Hueckman", "Hutcheson", "Rupinski", "Poduska", "Mccrumb", "Vanaller", "Rodkin", "Hansell", "Truan", "Loa", "Nienaber", "Boebinger", "Aquil", "Rzeszutko", "Wallack", "Zoellner", "Hargenrader", "Saris", "Hesson", "Dragan", "Klemisch", "Robblee", "Mabray", "Stankiewicz", "Kraus", "Wik", "Pickett",
            "Laskosky", "Hayn", "Loche", "Kotaki", "Thramer", "Baranick", "Geier", "Carrington", "Neufeld", "Shone", "Poles", "Hyten", "Hendryx", "Naz", "Gallian", "Colbath", "Guardia", "Nishi", "Lemarie", "Kittleson", "Stenberg", "Stoodley", "Mcgregor", "Steptoe", "Parduhn", "Solages", "Shatley", "Skanes", "Wittbrodt", "Womac", "Gorley", "Moorman"};

    public static String getRandomSurname() {
        int ran0 = (int) (Math.random() * (surnames.length));
        return surnames[ran0];
    }

    public static void main(String[] args) {
        System.out.println(getRandomSurname());
    }
}
